"""empty message

Revision ID: 227c848483ee
Revises: 
Create Date: 2017-05-07 20:49:44.184895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227c848483ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
